import CodexAIGC.Classification.DimensionThreeRealComplexStraightReduction
import Mathlib.Algebra.Polynomial.Degree.IsMonicOfDegree
import Mathlib.Analysis.Polynomial.Order
import Mathlib.Tactic.ComputeDegree

/-!
# Algebraic reduction for the unital sector

This file begins the independent completeness proof for three-dimensional
unital associative algebras.  A unital algebra is called *unitally straight*
when some element `x` makes `(1,x,x²)` a basis.  Associativity then forces the
entire multiplication from one cubic relation

`x³ = d 1 + b x + a x²`.

The resulting three-parameter table is constructed explicitly, proved
associative for every parameter, and shown to represent every unitally-straight
table.  Later results split this cubic relation by its root pattern over `ℂ`
and `ℝ`.
-/

namespace CodexAIGC.DimensionThreeRealComplex

open StructureConstants
open Polynomial

universe u

variable {K : Type u} [Field K]

/-! ## The cubic relation and its roots -/

/-- The monic polynomial encoding `x³ = d + b x + a x²`. -/
noncomputable def cubicRelationPolynomial (a b d : K) : K[X] :=
  X ^ 3 - C a * X ^ 2 - C b * X - C d

theorem cubicRelationPolynomial_isMonicOfDegree (a b d : K) :
    IsMonicOfDegree (cubicRelationPolynomial a b d) 3 := by
  rw [isMonicOfDegree_iff]
  constructor
  · unfold cubicRelationPolynomial
    compute_degree
  · simp [cubicRelationPolynomial, coeff_sub]

/-- The quadratic factor left after selecting a root `r` of the cubic. -/
noncomputable def residualQuadraticPolynomial (p q : K) : K[X] :=
  X ^ 2 + C p * X + C q

theorem residualQuadraticPolynomial_isMonicOfDegree (p q : K) :
    IsMonicOfDegree (residualQuadraticPolynomial p q) 2 := by
  simpa [residualQuadraticPolynomial] using isMonicOfDegree_add_add_two p q

/-- A cubic relation over an algebraically closed field has three roots,
counted with multiplicity, whose elementary symmetric functions recover its
three coefficients. -/
theorem cubicRelation_coefficients_split [IsAlgClosed K] (a b d : K) :
    ∃ r s t : K,
      a = r + s + t ∧
      b = -(r * s + r * t + s * t) ∧
      d = r * s * t := by
  have hcm := cubicRelationPolynomial_isMonicOfDegree a b d
  have hcdeg : (cubicRelationPolynomial a b d).degree ≠ 0 := by
    rw [degree_eq_natDegree hcm.ne_zero, hcm.natDegree_eq]
    norm_num
  obtain ⟨r, hrroot⟩ :=
    IsAlgClosed.exists_root (cubicRelationPolynomial a b d) hcdeg
  have hr : r ^ 3 = a * r ^ 2 + b * r + d := by
    have he : r ^ 3 - a * r ^ 2 - b * r - d = 0 := by
      simpa [cubicRelationPolynomial] using hrroot
    linear_combination he
  let p := r - a
  let q := r ^ 2 - a * r - b
  have hqm := residualQuadraticPolynomial_isMonicOfDegree p q
  have hqdeg : (residualQuadraticPolynomial p q).degree ≠ 0 := by
    rw [degree_eq_natDegree hqm.ne_zero, hqm.natDegree_eq]
    norm_num
  obtain ⟨s, hsroot⟩ :=
    IsAlgClosed.exists_root (residualQuadraticPolynomial p q) hqdeg
  have hs : s ^ 2 + (r - a) * s + (r ^ 2 - a * r - b) = 0 := by
    simpa [residualQuadraticPolynomial, p, q] using hsroot
  let t := a - r - s
  refine ⟨r, s, t, ?_, ?_, ?_⟩
  · simp [t]
  · dsimp [t]
    linear_combination -hs
  · dsimp [t]
    linear_combination r * hs - hr

/-- A real monic cubic has a real root.  This proof is internal: assuming no
root, the eventual-sign theorems force its value at zero to be simultaneously
positive and negative. -/
theorem real_cubicRelation_root_exists (a b d : ℝ) :
    ∃ r : ℝ, r ^ 3 = a * r ^ 2 + b * r + d := by
  have hcm := cubicRelationPolynomial_isMonicOfDegree a b d
  by_contra hnone
  rw [not_exists] at hnone
  have hnoRoot : ∀ y : ℝ, ¬(cubicRelationPolynomial a b d).IsRoot y := by
    intro y hy
    apply hnone y
    have he : y ^ 3 - a * y ^ 2 - b * y - d = 0 := by
      simpa [cubicRelationPolynomial] using hy
    linear_combination he
  have hpos : 0 < (cubicRelationPolynomial a b d).eval 0 :=
    zero_lt_eval_of_roots_lt_of_leadingCoeff_nonneg
      (fun y hy => (hnoRoot y hy).elim)
      (by rw [hcm.leadingCoeff_eq]; norm_num)
  have hleft :
      0 < Int.negOnePow (cubicRelationPolynomial a b d).natDegree *
        (cubicRelationPolynomial a b d).eval 0 :=
    zero_lt_negOnePow_mul_eval_of_lt_roots_of_leadingCoeff_nonneg
      (fun y hy => (hnoRoot y hy).elim)
      (by rw [hcm.leadingCoeff_eq]; norm_num)
  rw [hcm.natDegree_eq] at hleft
  norm_num at hleft
  linarith

/-- Coordinate vector for the cubic relation
`x³ = d 1 + b x + a x²`. -/
def unitalCubicThird (a b d : K) : V K :=
  d • e0 + b • e1 + a • e2

/-- Coordinates of `x⁴`, forced by the cubic relation. -/
def unitalCubicFourth (a b d : K) : V K :=
  (a * d) • e0 + (d + a * b) • e1 + (b + a * a) • e2

/-- The unital multiplication table generated by `1,x,x²` with
`x³ = d 1 + b x + a x²`. -/
def unitalCubicTable (a b d : K) : StructureConstants K 3 :=
  tableOfProducts e0 e1 e2
    e1 e2 (unitalCubicThird a b d)
    e2 (unitalCubicThird a b d) (unitalCubicFourth a b d)

/-- Every cubic power table is genuinely associative. -/
theorem unitalCubicTable_multiplicationAssociative (a b d : K) :
    (unitalCubicTable a b d).MultiplicationAssociative := by
  intro x y z
  apply funext_three <;>
    simp [unitalCubicTable, unitalCubicThird, unitalCubicFourth,
      tableOfProducts, e0, e1, e2, mul, Fin.sum_univ_three] <;>
    ring

/-- The first standard basis vector is the two-sided identity of every cubic
power table. -/
theorem unitalCubicTable_hasTwoSidedIdentity (a b d : K) :
    HasTwoSidedIdentity (unitalCubicTable a b d) := by
  refine ⟨e0, ?_⟩
  intro x
  constructor <;>
    apply funext_three <;>
    simp [unitalCubicTable, unitalCubicThird, unitalCubicFourth,
      tableOfProducts, e0, e1, e2, mul, Fin.sum_univ_three]

/-- A chosen identity and an element whose first two powers complete it to a
basis. -/
def HasUnitallyStraightGenerator (c : StructureConstants K 3) (one : V K) : Prop :=
  ∃ x, TripleIndependent one x (c.mul x x)

/-- Intrinsic unitally-straight condition, including the identity laws. -/
def IsUnitallyStraight (c : StructureConstants K 3) : Prop :=
  ∃ one, (∀ y, c.mul one y = y ∧ c.mul y one = y) ∧
    HasUnitallyStraightGenerator c one

/-- Coordinates of `x³` exist uniquely in the basis `(1,x,x²)`. -/
theorem unital_cubic_relation_exists
    {c : StructureConstants K 3} {one x : V K}
    (hlin : TripleIndependent one x (c.mul x x)) :
    ∃ a b d : K,
      c.mul (c.mul x x) x =
        d • one + b • x + a • c.mul x x := by
  let E := basisEquivOfTripleIndependent hlin
  let x3 := c.mul (c.mul x x) x
  let q := E.symm x3
  refine ⟨q 2, q 1, q 0, ?_⟩
  calc
    x3 = E (E.symm x3) := (E.apply_symm_apply x3).symm
    _ = q 0 • one + q 1 • x + q 2 • c.mul x x := by
      exact basisEquivOfTripleIndependent_apply hlin q

/-- An associative table with identity `one` and basis `(one,x,x²)` is
explicitly equivalent to its cubic power table. -/
noncomputable def unitalCubicTableEquiv
    {c : StructureConstants K 3} (ha : c.MultiplicationAssociative)
    {one x : V K}
    (hu : ∀ y, c.mul one y = y ∧ c.mul y one = y)
    (hlin : TripleIndependent one x (c.mul x x))
    (a b d : K)
    (h3 : c.mul (c.mul x x) x =
      d • one + b • x + a • c.mul x x) :
    TableEquiv (unitalCubicTable a b d) c := by
  let x2 := c.mul x x
  let x3 := c.mul x2 x
  let x4 := (a * d) • one + (d + a * b) • x + (b + a * a) • x2
  have hlin' : TripleIndependent one x x2 := by
    simpa [x2] using hlin
  have h3' : x3 = d • one + b • x + a • x2 := by
    simpa [x2, x3] using h3
  have hxx : c.mul x x = x2 := rfl
  have hx2x : c.mul x2 x = x3 := rfl
  have hxx2 : c.mul x x2 = x3 := by
    change c.mul x (c.mul x x) = c.mul (c.mul x x) x
    exact (ha x x x).symm
  have hxx3 : c.mul x x3 = x4 := by
    rw [h3']
    change (mulLinear c x) (d • one + b • x + a • x2) = x4
    rw [map_add, map_add, map_smul, map_smul, map_smul,
      mulLinear_apply, mulLinear_apply, mulLinear_apply,
      (hu x).2, hxx, hxx2, h3']
    apply funext_three <;> simp [x4] <;> ring
  have hx2x2 : c.mul x2 x2 = x4 := by
    calc
      c.mul x2 x2 = c.mul (c.mul x x) x2 := by rfl
      _ = c.mul x (c.mul x x2) := ha x x x2
      _ = c.mul x x3 := by rw [hxx2]
      _ = x4 := hxx3
  let E := basisEquivOfTripleIndependent hlin'
  have hE3 : E (unitalCubicThird a b d) = x3 := by
    rw [basisEquivOfTripleIndependent_apply]
    simpa [unitalCubicThird, e0, e1, e2] using h3'.symm
  have hE4 : E (unitalCubicFourth a b d) = x4 := by
    rw [basisEquivOfTripleIndependent_apply]
    simp [unitalCubicFourth, e0, e1, e2, x4]
  exact TableEquiv.ofBasis E (by
    intro i j
    fin_cases i <;> fin_cases j <;>
      simp [unitalCubicTable, E, hE3, hE4, hu, hxx, hxx2,
        hx2x, hx2x2])

/-- Every associative unitally-straight table is represented by a cubic power
table. -/
theorem unitallyStraight_isomorphic_unitalCubicTable
    {c : StructureConstants K 3} (ha : c.MultiplicationAssociative)
    (hs : IsUnitallyStraight c) :
    ∃ a b d : K, Isomorphic c (unitalCubicTable a b d) := by
  obtain ⟨one, hu, x, hlin⟩ := hs
  obtain ⟨a, b, d, h3⟩ := unital_cubic_relation_exists hlin
  exact ⟨a, b, d, ⟨(unitalCubicTableEquiv ha hu hlin a b d h3).symm⟩⟩

/-! ## Cubics with a triple root -/

/-- Translation by a triple root changes the cubic generator into a nilpotent
generator of order three. -/
theorem unitalCubicTable_tripleRoot_isomorphic_u4 (r : K) :
    Isomorphic
      (unitalCubicTable (3 * r) (-3 * r * r) (r * r * r))
      (fixedTable .u4) := by
  let one : V K := e0
  let y : V K := e1 - r • e0
  let y2 : V K := e2 - (2 * r) • e1 + (r * r) • e0
  have hlin : TripleIndependent one y y2 := by
    rw [TripleIndependent, Fintype.linearIndependent_iff]
    intro s hrel
    have hrel' : s 0 • one + s 1 • y + s 2 • y2 = 0 := by
      simpa [Fin.sum_univ_three] using hrel
    have hcoord0 := congrFun hrel' 0
    have hcoord1 := congrFun hrel' 1
    have hcoord2 := congrFun hrel' 2
    have hs2 : s 2 = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord2
    have hs1 : s 1 = 0 := by
      simpa [one, y, y2, e0, e1, e2, hs2] using hcoord1
    have hs0 : s 0 = 0 := by
      simpa [one, y, y2, e0, e1, e2, hs1, hs2] using hcoord0
    intro i
    fin_cases i
    · exact hs0
    · exact hs1
    · exact hs2
  let E := basisEquivOfTripleIndependent hlin
  let T : TableEquiv (fixedTable (K := K) .u4)
      (unitalCubicTable (3 * r) (-3 * r * r) (r * r * r)) :=
    TableEquiv.ofBasis E (by
      intro i j
      fin_cases i <;> fin_cases j <;>
        simp [fixedTable, E] <;>
        apply funext_three <;>
        simp [one, y, y2, unitalCubicTable, unitalCubicThird,
          unitalCubicFourth, tableOfProducts, e0, e1, e2, mul,
          Fin.sum_univ_three] <;>
        ring)
  exact ⟨T.symm⟩

/-! ## Cubics with one simple and one double root -/

/-- A cubic with distinct roots `r` and `s`, where `s` has multiplicity two,
is the product of a field factor and the dual numbers.  The proof uses the
explicit generator `(r, s + ε)` in `U3`. -/
theorem unitalCubicTable_simpleDouble_isomorphic_u3
    (r s : K) (hrs : r ≠ s) :
    Isomorphic
      (unitalCubicTable (r + 2 * s) (-(2 * r * s + s * s)) (r * s * s))
      (fixedTable .u3) := by
  let one : V K := e0 + e1
  let y : V K := r • e0 + s • e1 + e2
  let y2 : V K := (r * r) • e0 + (s * s) • e1 + (2 * s) • e2
  have hlin : TripleIndependent one y y2 := by
    rw [TripleIndependent, Fintype.linearIndependent_iff]
    intro q hrel
    have hrel' : q 0 • one + q 1 • y + q 2 • y2 = 0 := by
      simpa [Fin.sum_univ_three] using hrel
    have hcoord0 := congrFun hrel' 0
    have hcoord1 := congrFun hrel' 1
    have hcoord2 := congrFun hrel' 2
    have h0 : q 0 + q 1 * r + q 2 * (r * r) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord0
    have h1 : q 0 + q 1 * s + q 2 * (s * s) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord1
    have h2 : q 1 + q 2 * (2 * s) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord2
    have hprod : (r - s) ^ 2 * q 2 = 0 := by
      linear_combination h0 - h1 - (r - s) * h2
    have hsquare : (r - s) ^ 2 ≠ 0 :=
      pow_ne_zero 2 (sub_ne_zero.mpr hrs)
    have hq2 : q 2 = 0 := (mul_eq_zero.mp hprod).resolve_left hsquare
    have hq1 : q 1 = 0 := by simpa [hq2] using h2
    have hq0 : q 0 = 0 := by simpa [hq1, hq2] using h0
    intro i
    fin_cases i
    · exact hq0
    · exact hq1
    · exact hq2
  let E := basisEquivOfTripleIndependent hlin
  let T : TableEquiv
      (unitalCubicTable (r + 2 * s) (-(2 * r * s + s * s)) (r * s * s))
      (fixedTable (K := K) .u3) :=
    TableEquiv.ofBasis E (by
      intro i j
      fin_cases i <;> fin_cases j <;>
        simp [unitalCubicTable, E, basisEquivOfTripleIndependent_apply] <;>
        apply funext_three <;>
        simp [one, y, y2, unitalCubicThird,
          unitalCubicFourth, fixedTable, tableOfProducts, e0, e1, e2,
          mul, Fin.sum_univ_three] <;>
        ring)
  exact ⟨T⟩

/-! ## Cubics with three distinct roots -/

/-- A split cubic with three pairwise distinct roots is the product algebra
`K × K × K`.  The equivalence is the explicit three-point evaluation map
in the basis `(1,x,x²)`. -/
theorem unitalCubicTable_threeDistinct_isomorphic_u2
    (r s t : K) (hrs : r ≠ s) (hrt : r ≠ t) (hst : s ≠ t) :
    Isomorphic
      (unitalCubicTable (r + s + t)
        (-(r * s + r * t + s * t)) (r * s * t))
      (fixedTable .u2) := by
  let one : V K := e0 + e1 + e2
  let y : V K := r • e0 + s • e1 + t • e2
  let y2 : V K := (r * r) • e0 + (s * s) • e1 + (t * t) • e2
  have hlin : TripleIndependent one y y2 := by
    rw [TripleIndependent, Fintype.linearIndependent_iff]
    intro q hrel
    have hrel' : q 0 • one + q 1 • y + q 2 • y2 = 0 := by
      simpa [Fin.sum_univ_three] using hrel
    have hcoord0 := congrFun hrel' 0
    have hcoord1 := congrFun hrel' 1
    have hcoord2 := congrFun hrel' 2
    have h0 : q 0 + q 1 * r + q 2 * (r * r) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord0
    have h1 : q 0 + q 1 * s + q 2 * (s * s) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord1
    have h2 : q 0 + q 1 * t + q 2 * (t * t) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord2
    have h01prod : (r - s) * (q 1 + (r + s) * q 2) = 0 := by
      linear_combination h0 - h1
    have h02prod : (r - t) * (q 1 + (r + t) * q 2) = 0 := by
      linear_combination h0 - h2
    have h01 : q 1 + (r + s) * q 2 = 0 :=
      (mul_eq_zero.mp h01prod).resolve_left (sub_ne_zero.mpr hrs)
    have h02 : q 1 + (r + t) * q 2 = 0 :=
      (mul_eq_zero.mp h02prod).resolve_left (sub_ne_zero.mpr hrt)
    have hstprod : (s - t) * q 2 = 0 := by
      linear_combination h01 - h02
    have hq2 : q 2 = 0 :=
      (mul_eq_zero.mp hstprod).resolve_left (sub_ne_zero.mpr hst)
    have hq1 : q 1 = 0 := by simpa [hq2] using h01
    have hq0 : q 0 = 0 := by simpa [hq1, hq2] using h0
    intro i
    fin_cases i
    · exact hq0
    · exact hq1
    · exact hq2
  let E := basisEquivOfTripleIndependent hlin
  let T : TableEquiv
      (unitalCubicTable (r + s + t)
        (-(r * s + r * t + s * t)) (r * s * t))
      (fixedTable (K := K) .u2) :=
    TableEquiv.ofBasis E (by
      intro i j
      fin_cases i <;> fin_cases j <;>
        simp [unitalCubicTable, E, basisEquivOfTripleIndependent_apply] <;>
        apply funext_three <;>
        simp [one, y, y2, unitalCubicThird, unitalCubicFourth,
          fixedTable, tableOfProducts, e0, e1, e2, mul,
          Fin.sum_univ_three] <;>
        ring)
  exact ⟨T⟩

/-- The three possible equality patterns among a complete list of cubic roots
give exactly `U2`, `U3`, or `U4`. -/
theorem unitalCubicTable_isomorphic_of_complete_split
    (a b d r s t : K)
    (ha : a = r + s + t)
    (hb : b = -(r * s + r * t + s * t))
    (hd : d = r * s * t) :
    Isomorphic (unitalCubicTable a b d) (fixedTable .u2) ∨
      Isomorphic (unitalCubicTable a b d) (fixedTable .u3) ∨
      Isomorphic (unitalCubicTable a b d) (fixedTable .u4) := by
  subst a
  subst b
  subst d
  by_cases hrs : r = s
  · subst s
    by_cases hrt : r = t
    · subst t
      right
      right
      have ha : r + r + r = 3 * r := by ring
      have hb : -(r * r + r * r + r * r) = -3 * r * r := by ring
      simpa only [ha, hb] using unitalCubicTable_tripleRoot_isomorphic_u4 r
    · right
      left
      have ha : r + r + t = t + 2 * r := by ring
      have hb : -(r * r + r * t + r * t) = -(2 * t * r + r * r) := by ring
      have hd : r * r * t = t * r * r := by ring
      simpa only [ha, hb, hd] using
        unitalCubicTable_simpleDouble_isomorphic_u3 t r (Ne.symm hrt)
  · by_cases hrt : r = t
    · subst t
      right
      left
      have ha : r + s + r = s + 2 * r := by ring
      have hb : -(r * s + r * r + s * r) = -(2 * s * r + r * r) := by ring
      have hd : r * s * r = s * r * r := by ring
      simpa only [ha, hb, hd] using
        unitalCubicTable_simpleDouble_isomorphic_u3 s r (Ne.symm hrs)
    · by_cases hst : s = t
      · subst t
        right
        left
        have ha : r + s + s = r + 2 * s := by ring
        have hb : -(r * s + r * s + s * s) = -(2 * r * s + s * s) := by ring
        simpa only [ha, hb] using
          unitalCubicTable_simpleDouble_isomorphic_u3 r s hrs
      · left
        exact unitalCubicTable_threeDistinct_isomorphic_u2 r s t hrs hrt hst

/-- Complete classification of cubic power tables over `ℂ`. -/
theorem complex_unitalCubicTable_classification (a b d : ℂ) :
    Isomorphic (unitalCubicTable a b d) (fixedTable .u2) ∨
      Isomorphic (unitalCubicTable a b d) (fixedTable .u3) ∨
      Isomorphic (unitalCubicTable a b d) (fixedTable .u4) := by
  obtain ⟨r, s, t, ha, hb, hd⟩ := cubicRelation_coefficients_split a b d
  exact unitalCubicTable_isomorphic_of_complete_split a b d r s t ha hb hd

/-! ## The real linear-times-irreducible-quadratic case -/

/-- Over `ℝ`, a real root together with a conjugate pair `u ± v i`
(`v ≠ 0`) gives the product algebra `ℝ × ℂ`.  The displayed generator is
`(r, u + v i)` in the audited real-minus table. -/
theorem real_unitalCubicTable_linearQuadratic_isomorphic_u2Minus
    (r u v : ℝ) (hv : v ≠ 0) :
    Isomorphic
      (unitalCubicTable (r + 2 * u)
        (-(u * u + v * v + 2 * r * u)) (r * (u * u + v * v)))
      realUnitalMinusTable := by
  let one : V ℝ := e0 + e1
  let y : V ℝ := r • e0 + u • e1 + v • e2
  let y2 : V ℝ := (r * r) • e0 + (u * u - v * v) • e1 + (2 * u * v) • e2
  have hlin : TripleIndependent one y y2 := by
    rw [TripleIndependent, Fintype.linearIndependent_iff]
    intro q hrel
    have hrel' : q 0 • one + q 1 • y + q 2 • y2 = 0 := by
      simpa [Fin.sum_univ_three] using hrel
    have hcoord0 := congrFun hrel' 0
    have hcoord1 := congrFun hrel' 1
    have hcoord2 := congrFun hrel' 2
    have h0 : q 0 + q 1 * r + q 2 * (r * r) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord0
    have h1 : q 0 + q 1 * u + q 2 * (u * u - v * v) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord1
    have h2 : q 1 * v + q 2 * (2 * u * v) = 0 := by
      simpa [one, y, y2, e0, e1, e2] using hcoord2
    have h2prod : v * (q 1 + 2 * u * q 2) = 0 := by
      linear_combination h2
    have h2base : q 1 + 2 * u * q 2 = 0 :=
      (mul_eq_zero.mp h2prod).resolve_left hv
    have hdiff :
        (r - u) * q 1 + (r * r - u * u + v * v) * q 2 = 0 := by
      linear_combination h0 - h1
    have hpositive : 0 < (r - u) ^ 2 + v ^ 2 := by
      nlinarith [sq_nonneg (r - u), sq_pos_of_ne_zero hv]
    have hq2prod : ((r - u) ^ 2 + v ^ 2) * q 2 = 0 := by
      linear_combination hdiff - (r - u) * h2base
    have hq2 : q 2 = 0 :=
      (mul_eq_zero.mp hq2prod).resolve_left hpositive.ne'
    have hq1 : q 1 = 0 := by simpa [hq2] using h2base
    have hq0 : q 0 = 0 := by simpa [hq1, hq2] using h0
    intro i
    fin_cases i
    · exact hq0
    · exact hq1
    · exact hq2
  let E := basisEquivOfTripleIndependent hlin
  let T : TableEquiv
      (unitalCubicTable (r + 2 * u)
        (-(u * u + v * v + 2 * r * u)) (r * (u * u + v * v)))
      realUnitalMinusTable :=
    TableEquiv.ofBasis E (by
      intro i j
      fin_cases i <;> fin_cases j <;>
        simp [unitalCubicTable, E, basisEquivOfTripleIndependent_apply] <;>
        apply funext_three <;>
        simp [one, y, y2, unitalCubicThird, unitalCubicFourth,
          realUnitalMinusTable, tableOfProducts, e0, e1, e2, mul,
          Fin.sum_univ_three] <;>
        ring)
  exact ⟨T⟩

/-- Complete classification of cubic power tables over `ℝ`.  A nonnegative
residual discriminant gives three real roots (with multiplicity); a negative
one gives the additional `ℝ × ℂ` form. -/
theorem real_unitalCubicTable_classification (a b d : ℝ) :
    (Isomorphic (unitalCubicTable a b d) (fixedTable .u2) ∨
      Isomorphic (unitalCubicTable a b d) (fixedTable .u3) ∨
      Isomorphic (unitalCubicTable a b d) (fixedTable .u4)) ∨
      Isomorphic (unitalCubicTable a b d) realUnitalMinusTable := by
  obtain ⟨r, hr⟩ := real_cubicRelation_root_exists a b d
  let p := r - a
  let q := r ^ 2 - a * r - b
  let disc := p ^ 2 - 4 * q
  by_cases hdisc : 0 ≤ disc
  · let w := Real.sqrt disc
    let s := (-p + w) / 2
    let t := a - r - s
    have hw : w ^ 2 = disc := Real.sq_sqrt hdisc
    have hs : s ^ 2 + (r - a) * s + (r ^ 2 - a * r - b) = 0 := by
      dsimp [s, w]
      dsimp [disc, p, q] at hw
      nlinarith
    have ha : a = r + s + t := by simp [t]
    have hb : b = -(r * s + r * t + s * t) := by
      dsimp [t]
      linear_combination -hs
    have hd : d = r * s * t := by
      dsimp [t]
      linear_combination r * hs - hr
    exact Or.inl
      (unitalCubicTable_isomorphic_of_complete_split a b d r s t ha hb hd)
  · have hdisc_neg : disc < 0 := lt_of_not_ge hdisc
    let u := (a - r) / 2
    let v := Real.sqrt (-disc) / 2
    have hnonneg : 0 ≤ -disc := le_of_lt (neg_pos.mpr hdisc_neg)
    have hw : (Real.sqrt (-disc)) ^ 2 = -disc := Real.sq_sqrt hnonneg
    have hq : u * u + v * v = q := by
      dsimp [u, v]
      dsimp [disc] at hw
      nlinarith
    have hvpos : 0 < v := by
      dsimp [v]
      exact div_pos (Real.sqrt_pos.2 (neg_pos.mpr hdisc_neg)) (by norm_num)
    have ha : a = r + 2 * u := by
      dsimp [u]
      ring
    have hb : b = -(u * u + v * v + 2 * r * u) := by
      rw [hq]
      dsimp [q, u]
      ring
    have hd : d = r * (u * u + v * v) := by
      rw [hq]
      dsimp [q]
      linear_combination -hr
    right
    simpa only [ha, hb, hd] using
      real_unitalCubicTable_linearQuadratic_isomorphic_u2Minus r u v hvpos.ne'

end CodexAIGC.DimensionThreeRealComplex
