import CodexAIGC.Classification.DimensionThreeRealComplexCurledReduction
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# Algebraic reduction for the straight sector

For a straight generator `x`, the vectors `x,x²,x³` form a basis.  This
file reconstructs the resulting power table from associativity rather than
assuming a literature normal form.  The relation is written

`x⁴ = d x + b x² + a x³`.

The nonunital sector will force `d = 0`; the remaining quadratic discriminant
`a²+4b` controls the final real and complex normal forms.
-/

namespace CodexAIGC.DimensionThreeRealComplex

open StructureConstants

universe u

variable {K : Type u} [Field K]

/-- Coordinate vector for the fourth power relation. -/
def straightFourth (a b d : K) : V K :=
  d • e0 + b • e1 + a • e2

/-- Coordinates of the fifth power forced by the fourth power relation. -/
def straightFifth (a b d : K) : V K :=
  (a * d) • e0 + (d + a * b) • e1 + (b + a * a) • e2

/-- Coordinates of the sixth power forced by the fourth power relation. -/
def straightSixth (a b d : K) : V K :=
  (d * (b + a * a)) • e0 +
    (b * b + a * d + a * a * b) • e1 +
      (d + 2 * a * b + a * a * a) • e2

/-- The multiplication table generated by `x,x²,x³` with
`x⁴ = d x + b x² + a x³`. -/
def straightPowerTable (a b d : K) : StructureConstants K 3 :=
  tableOfProducts e1 e2 (straightFourth a b d)
    e2 (straightFourth a b d) (straightFifth a b d)
    (straightFourth a b d) (straightFifth a b d) (straightSixth a b d)

/-- Every three-parameter power table is genuinely associative. -/
theorem straightPowerTable_multiplicationAssociative (a b d : K) :
    (straightPowerTable a b d).MultiplicationAssociative := by
  intro x y z
  apply funext_three <;>
    simp [straightPowerTable, straightFourth, straightFifth, straightSixth,
      tableOfProducts, e0, e1, e2, mul, Fin.sum_univ_three] <;>
    ring

/-- A straight basis provides unique coordinates for the fourth power. -/
theorem straight_fourthPower_relation_exists
    {c : StructureConstants K 3} {x : V K}
    (hlin : TripleIndependent x (c.mul x x) (c.mul (c.mul x x) x)) :
    ∃ a b d : K,
      c.mul (c.mul (c.mul x x) x) x =
        d • x + b • c.mul x x + a • c.mul (c.mul x x) x := by
  let E := basisEquivOfTripleIndependent hlin
  let x4 := c.mul (c.mul (c.mul x x) x) x
  let q := E.symm x4
  refine ⟨q 2, q 1, q 0, ?_⟩
  calc
    x4 = E (E.symm x4) := (E.apply_symm_apply x4).symm
    _ = q 0 • x + q 1 • c.mul x x + q 2 • c.mul (c.mul x x) x := by
      exact basisEquivOfTripleIndependent_apply hlin q

/-- The basis `x,x²,x³` identifies an arbitrary associative straight table
with its three-parameter power table. -/
noncomputable def straightPowerTableEquiv
    {c : StructureConstants K 3} (ha : c.MultiplicationAssociative)
    {x : V K}
    (hlin : TripleIndependent x (c.mul x x) (c.mul (c.mul x x) x))
    (a b d : K)
    (h4 : c.mul (c.mul (c.mul x x) x) x =
      d • x + b • c.mul x x + a • c.mul (c.mul x x) x) :
    TableEquiv (straightPowerTable a b d) c := by
  let x2 := c.mul x x
  let x3 := c.mul x2 x
  let x4 := c.mul x3 x
  let x5 := (a * d) • x + (d + a * b) • x2 + (b + a * a) • x3
  let x6 := (d * (b + a * a)) • x +
    (b * b + a * d + a * a * b) • x2 +
      (d + 2 * a * b + a * a * a) • x3
  have hlin' : TripleIndependent x x2 x3 := by
    simpa [x2, x3] using hlin
  have h4' : x4 = d • x + b • x2 + a • x3 := by
    simpa [x2, x3, x4] using h4
  have hxx : c.mul x x = x2 := rfl
  have hx2x : c.mul x2 x = x3 := rfl
  have hxx2 : c.mul x x2 = x3 := by
    change c.mul x (c.mul x x) = c.mul (c.mul x x) x
    exact (ha x x x).symm
  have hx3x : c.mul x3 x = x4 := rfl
  have hxx3 : c.mul x x3 = x4 := by
    calc
      c.mul x x3 = c.mul x (c.mul x2 x) := by rfl
      _ = c.mul (c.mul x x2) x := (ha x x2 x).symm
      _ = c.mul x3 x := by rw [hxx2]
      _ = x4 := hx3x
  have hx2x2 : c.mul x2 x2 = x4 := by
    calc
      c.mul x2 x2 = c.mul (c.mul x x) x2 := by rfl
      _ = c.mul x (c.mul x x2) := ha x x x2
      _ = c.mul x x3 := by rw [hxx2]
      _ = x4 := hxx3
  have hxx4 : c.mul x x4 = x5 := by
    rw [h4']
    change (mulLinear c x) (d • x + b • x2 + a • x3) = x5
    rw [map_add, map_add, map_smul, map_smul, map_smul,
      mulLinear_apply, mulLinear_apply, mulLinear_apply, hxx, hxx2, hxx3, h4']
    apply funext_three <;> simp [x5] <;> ring
  have hx2x3 : c.mul x2 x3 = x5 := by
    calc
      c.mul x2 x3 = c.mul x (c.mul x x3) := ha x x x3
      _ = c.mul x x4 := by rw [hxx3]
      _ = x5 := hxx4
  have hx3x2 : c.mul x3 x2 = x5 := by
    have hcomm := ha x2 x x2
    rw [hx2x, hxx2] at hcomm
    exact hcomm.trans hx2x3
  have hx3x3 : c.mul x3 x3 = x6 := by
    calc
      c.mul x3 x3 = c.mul x2 (c.mul x x3) := by
        have hp := ha x2 x x3
        rw [hx2x] at hp
        exact hp
      _ = c.mul x2 x4 := by rw [hxx3]
      _ = c.mul x2 (d • x + b • x2 + a • x3) := by rw [h4']
      _ = d • x3 + b • x4 + a • x5 := by
        change (mulLinear c x2) (d • x + b • x2 + a • x3) = _
        rw [map_add, map_add, map_smul, map_smul, map_smul,
          mulLinear_apply, mulLinear_apply, mulLinear_apply, hx2x, hx2x2, hx2x3]
      _ = x6 := by
        rw [h4']
        apply funext_three <;> simp [x5, x6] <;> ring
  let E := basisEquivOfTripleIndependent hlin'
  have hE4 : E (straightFourth a b d) = x4 := by
    rw [basisEquivOfTripleIndependent_apply]
    simpa [straightFourth, e0, e1, e2] using h4'.symm
  have hE5 : E (straightFifth a b d) = x5 := by
    rw [basisEquivOfTripleIndependent_apply]
    simp [straightFifth, e0, e1, e2, x5]
  have hE6 : E (straightSixth a b d) = x6 := by
    rw [basisEquivOfTripleIndependent_apply]
    simp [straightSixth, e0, e1, e2, x6]
  exact TableEquiv.ofBasis E (by
    intro i j
    fin_cases i <;> fin_cases j <;>
      simp [straightPowerTable, E, hE4, hE5, hE6, hxx, hxx2, hxx3,
        hx2x, hx2x2, hx2x3, hx3x, hx3x2, hx3x3])

theorem straight_isomorphic_powerTable
    {c : StructureConstants K 3} (ha : c.MultiplicationAssociative)
    {x : V K}
    (hlin : TripleIndependent x (c.mul x x) (c.mul (c.mul x x) x)) :
    ∃ a b d : K, Isomorphic c (straightPowerTable a b d) := by
  obtain ⟨a, b, d, h4⟩ := straight_fourthPower_relation_exists hlin
  exact ⟨a, b, d, ⟨(straightPowerTableEquiv ha hlin a b d h4).symm⟩⟩

/-- A nonzero coefficient of `x` in the fourth-power relation produces an
explicit identity element. -/
theorem straightPowerTable_hasTwoSidedIdentity_of_d_ne
    (a b d : K) (hd : d ≠ 0) :
    HasTwoSidedIdentity (straightPowerTable a b d) := by
  let oneA : V K := d⁻¹ • (e2 - a • e1 - b • e0)
  refine ⟨oneA, ?_⟩
  intro y
  constructor <;>
    apply funext_three <;>
    simp [oneA, straightPowerTable, straightFourth, straightFifth,
      straightSixth, tableOfProducts, e0, e1, e2, mul,
      Fin.sum_univ_three] <;>
    field_simp [hd] <;>
    ring

/-- In the nonunital straight sector, the fourth-power relation has no `x`
term. -/
theorem nonunital_straight_isomorphic_powerTable_zero
    {c : StructureConstants K 3} (ha : c.MultiplicationAssociative)
    (hsector : InSector c .straight) :
    ∃ a b : K, Isomorphic c (straightPowerTable a b 0) := by
  obtain ⟨x, hlin⟩ := hsector.2
  obtain ⟨a, b, d, h4⟩ := straight_fourthPower_relation_exists hlin
  have hiso : Isomorphic c (straightPowerTable a b d) :=
    ⟨(straightPowerTableEquiv ha hlin a b d h4).symm⟩
  have hd0 : d = 0 := by
    by_contra hd
    apply hsector.1
    exact (hasTwoSidedIdentity_iff_of_isomorphic hiso).mpr
      (straightPowerTable_hasTwoSidedIdentity_of_d_ne a b d hd)
  subst d
  exact ⟨a, b, hiso⟩

/-! ## First two discriminant cases -/

theorem straightPowerTable_zero_zero_eq_s1 :
    straightPowerTable (K := K) 0 0 0 = fixedTable .s1 := by
  apply (coeffEquiv K 3).injective
  funext i j k
  fin_cases i <;> fin_cases j <;> fin_cases k <;>
    simp [straightPowerTable, straightFourth, straightFifth, straightSixth,
      fixedTable, tableOfProducts, e0, e1, e2]

/-- When `b=0` but `a≠0`, an explicit rescaled power basis gives `S2`. -/
theorem straightPowerTable_b_zero_isomorphic_s2
    (a : K) (ha0 : a ≠ 0) :
    Isomorphic (straightPowerTable a 0 0) (fixedTable .s2) := by
  let p : V K := (a ^ 3)⁻¹ • e2
  let q : V K := a⁻¹ • e0 - p
  let r : V K := (a ^ 2)⁻¹ • e1 - p
  have hlin : TripleIndependent p q r := by
    rw [TripleIndependent, Fintype.linearIndependent_iff]
    intro s hrel
    have hrel' : s 0 • p + s 1 • q + s 2 • r = 0 := by
      simpa [Fin.sum_univ_three] using hrel
    have hcoord0 := congrFun hrel' 0
    have hcoord1 := congrFun hrel' 1
    have hcoord2 := congrFun hrel' 2
    have hs1 : s 1 = 0 := by
      simp [p, q, r, e0, e1, e2, ha0] at hcoord0
      exact hcoord0
    have hs2 : s 2 = 0 := by
      simp [p, q, r, e0, e1, e2, ha0] at hcoord1
      exact hcoord1
    have hs0 : s 0 = 0 := by
      simp [p, q, r, e0, e1, e2, ha0, hs1, hs2] at hcoord2
      exact hcoord2
    intro i
    fin_cases i
    · exact hs0
    · exact hs1
    · exact hs2
  let E := basisEquivOfTripleIndependent hlin
  let T : TableEquiv (fixedTable (K := K) .s2)
      (straightPowerTable a 0 0) :=
    TableEquiv.ofBasis E (by
      intro i j
      fin_cases i <;> fin_cases j <;>
        simp [fixedTable, E] <;>
        apply funext_three <;>
        simp [p, q, r, straightPowerTable, straightFourth, straightFifth,
          straightSixth, tableOfProducts, e0, e1, e2, mul,
          Fin.sum_univ_three] <;>
        field_simp [ha0] <;>
        ring)
  exact ⟨T.symm⟩

/-! ## The `b ≠ 0` block and its discriminant -/

def straightDiscriminant (a b : K) : K := a * a + 4 * b

/-- The one-dimensional annihilator summand. -/
def straightBlockAnnihilator (a b : K) : V K :=
  e2 - a • e1 - b • e0

/-- Identity of the complementary two-dimensional algebra. -/
def straightBlockUnit (a b : K) : V K :=
  (b ^ 2)⁻¹ • ((a * a + b) • e1 - a • e2)

/-- A generator of the complementary two-dimensional algebra. -/
def straightBlockGenerator (a b : K) : V K :=
  b⁻¹ • (e2 - a • e1)

/-- The centered generator whose square is one quarter of the discriminant. -/
def straightCenteredGenerator (a b : K) : V K :=
  straightBlockGenerator a b - (a / 2) • straightBlockUnit a b

theorem straightBlockAnnihilator_mul (a b : K) (x : V K) :
    (straightPowerTable a b 0).mul (straightBlockAnnihilator a b) x = 0 := by
  apply funext_three <;>
    simp [straightBlockAnnihilator, straightPowerTable, straightFourth,
      straightFifth, straightSixth, tableOfProducts, e0, e1, e2, mul,
      Fin.sum_univ_three] <;>
    ring

theorem straightBlock_mul_annihilator (a b : K) (x : V K) :
    (straightPowerTable a b 0).mul x (straightBlockAnnihilator a b) = 0 := by
  apply funext_three <;>
    simp [straightBlockAnnihilator, straightPowerTable, straightFourth,
      straightFifth, straightSixth, tableOfProducts, e0, e1, e2, mul,
      Fin.sum_univ_three] <;>
    ring

theorem straightBlockUnit_mul_self (a b : K) (hb : b ≠ 0) :
    (straightPowerTable a b 0).mul (straightBlockUnit a b)
      (straightBlockUnit a b) = straightBlockUnit a b := by
  apply funext_three <;>
    simp [straightBlockUnit, straightPowerTable, straightFourth, straightFifth,
      straightSixth, tableOfProducts, e0, e1, e2, mul,
      Fin.sum_univ_three] <;>
    field_simp [hb] <;>
    ring

theorem straightBlockUnit_mul_generator (a b : K) (hb : b ≠ 0) :
    (straightPowerTable a b 0).mul (straightBlockUnit a b)
      (straightBlockGenerator a b) = straightBlockGenerator a b := by
  apply funext_three <;>
    simp [straightBlockUnit, straightBlockGenerator, straightPowerTable,
      straightFourth, straightFifth, straightSixth, tableOfProducts,
      e0, e1, e2, mul, Fin.sum_univ_three] <;>
    field_simp [hb] <;>
    ring

theorem straightBlockGenerator_mul_unit (a b : K) (hb : b ≠ 0) :
    (straightPowerTable a b 0).mul (straightBlockGenerator a b)
      (straightBlockUnit a b) = straightBlockGenerator a b := by
  apply funext_three <;>
    simp [straightBlockUnit, straightBlockGenerator, straightPowerTable,
      straightFourth, straightFifth, straightSixth, tableOfProducts,
      e0, e1, e2, mul, Fin.sum_univ_three] <;>
    field_simp [hb] <;>
    ring

theorem straightBlockGenerator_mul_self (a b : K) (hb : b ≠ 0) :
    (straightPowerTable a b 0).mul (straightBlockGenerator a b)
      (straightBlockGenerator a b) =
        b • straightBlockUnit a b + a • straightBlockGenerator a b := by
  apply funext_three <;>
    simp [straightBlockUnit, straightBlockGenerator, straightPowerTable,
      straightFourth, straightFifth, straightSixth, tableOfProducts,
      e0, e1, e2, mul, Fin.sum_univ_three] <;>
    field_simp [hb] <;>
    ring

/-- The block unit, block generator, and annihilator vector form a basis. -/
theorem straightBlock_tripleIndependent (a b : K) (hb : b ≠ 0) :
    TripleIndependent (straightBlockUnit a b) (straightBlockGenerator a b)
      (straightBlockAnnihilator a b) := by
  rw [TripleIndependent, Fintype.linearIndependent_iff]
  intro s hrel
  have hrel' :
      s 0 • straightBlockUnit a b + s 1 • straightBlockGenerator a b +
        s 2 • straightBlockAnnihilator a b = 0 := by
    simpa [Fin.sum_univ_three] using hrel
  have hcoord0 := congrFun hrel' 0
  have hcoord1 := congrFun hrel' 1
  have hcoord2 := congrFun hrel' 2
  have hs2 : s 2 = 0 := by
    simp [straightBlockUnit, straightBlockGenerator, straightBlockAnnihilator,
      e0, e1, e2, hb] at hcoord0
    exact hcoord0
  have hs0 : s 0 = 0 := by
    simp [straightBlockUnit, straightBlockGenerator, straightBlockAnnihilator,
      e0, e1, e2, hs2] at hcoord1 hcoord2
    field_simp [hb] at hcoord1 hcoord2
    have hsb : s 0 * b = 0 := by
      linear_combination hcoord1 + a * hcoord2
    exact (mul_eq_zero.mp hsb).resolve_right hb
  have hs1 : s 1 = 0 := by
    simp [straightBlockUnit, straightBlockGenerator, straightBlockAnnihilator,
      e0, e1, e2, hb, hs0, hs2] at hcoord2
    exact hcoord2
  intro i
  fin_cases i
  · exact hs0
  · exact hs1
  · exact hs2

theorem straightCentered_mul_self [CharZero K]
    (a b : K) (hb : b ≠ 0) :
    (straightPowerTable a b 0).mul (straightCenteredGenerator a b)
      (straightCenteredGenerator a b) =
        (straightDiscriminant a b / 4) • straightBlockUnit a b := by
  apply funext_three <;>
    simp [straightCenteredGenerator, straightDiscriminant, straightBlockUnit,
      straightBlockGenerator, straightPowerTable, straightFourth,
      straightFifth, straightSixth, tableOfProducts, e0, e1, e2, mul,
      Fin.sum_univ_three] <;>
    field_simp [hb] <;>
    ring

theorem straightBlockUnit_mul_centered [CharZero K]
    (a b : K) (hb : b ≠ 0) :
    (straightPowerTable a b 0).mul (straightBlockUnit a b)
      (straightCenteredGenerator a b) = straightCenteredGenerator a b := by
  apply funext_three <;>
    simp [straightCenteredGenerator, straightBlockUnit, straightBlockGenerator,
      straightPowerTable, straightFourth, straightFifth, straightSixth,
      tableOfProducts, e0, e1, e2, mul, Fin.sum_univ_three] <;>
    field_simp [hb] <;>
    ring

theorem straightCentered_mul_blockUnit [CharZero K]
    (a b : K) (hb : b ≠ 0) :
    (straightPowerTable a b 0).mul (straightCenteredGenerator a b)
      (straightBlockUnit a b) = straightCenteredGenerator a b := by
  apply funext_three <;>
    simp [straightCenteredGenerator, straightBlockUnit, straightBlockGenerator,
      straightPowerTable, straightFourth, straightFifth, straightSixth,
      tableOfProducts, e0, e1, e2, mul, Fin.sum_univ_three] <;>
    field_simp [hb] <;>
    ring

theorem straightCentered_tripleIndependent [CharZero K]
    (a b : K) (hb : b ≠ 0) :
    TripleIndependent (straightBlockUnit a b) (straightCenteredGenerator a b)
      (straightBlockAnnihilator a b) := by
  have h := tripleIndependent_sub_smul_first
    (straightBlock_tripleIndependent a b hb) (a / 2) 0
  simpa [straightCenteredGenerator] using h

theorem tripleIndependent_smul_second {x y z : V K}
    (h : TripleIndependent x y z) {s : K} (hs : s ≠ 0) :
    TripleIndependent x (s • y) z := by
  rw [TripleIndependent, Fintype.linearIndependent_iff] at h ⊢
  intro g hrel
  let k : Fin 3 → K := at3 (g 0) (g 1 * s) (g 2)
  have hkrel : ∑ i, k i • at3 x y z i = 0 := by
    simp [k, Fin.sum_univ_three]
    calc
      g 0 • x + (g 1 * s) • y + g 2 • z =
          g 0 • x + g 1 • (s • y) + g 2 • z := by
        apply funext_three <;> simp <;> ring
      _ = 0 := by simpa [Fin.sum_univ_three] using hrel
  have hg0 : g 0 = 0 := by
    have hk0 := h k hkrel 0
    simpa [k] using hk0
  have hg1s : g 1 * s = 0 := by
    have hk1 := h k hkrel 1
    simpa [k] using hk1
  have hg1 : g 1 = 0 := (mul_eq_zero.mp hg1s).resolve_right hs
  have hg2 : g 2 = 0 := by
    have hk2 := h k hkrel 2
    simpa [k] using hk2
  intro i
  fin_cases i
  · exact hg0
  · exact hg1
  · exact hg2

/-- Vanishing discriminant gives the dual-number block `S4`. -/
theorem straightPowerTable_discriminant_zero_isomorphic_s4 [CharZero K]
    (a b : K) (hb : b ≠ 0) (hD : straightDiscriminant a b = 0) :
    Isomorphic (straightPowerTable a b 0) (fixedTable .s4) := by
  let p := straightBlockUnit a b
  let q := straightCenteredGenerator a b
  let r := straightBlockAnnihilator a b
  have hlin : TripleIndependent p q r :=
    straightCentered_tripleIndependent a b hb
  have hpp : (straightPowerTable a b 0).mul p p = p :=
    straightBlockUnit_mul_self a b hb
  have hpq : (straightPowerTable a b 0).mul p q = q :=
    straightBlockUnit_mul_centered a b hb
  have hqp : (straightPowerTable a b 0).mul q p = q :=
    straightCentered_mul_blockUnit a b hb
  have hqq : (straightPowerTable a b 0).mul q q = 0 := by
    rw [show q = straightCenteredGenerator a b by rfl,
      straightCentered_mul_self a b hb, hD]
    simp
  have hrLeft (x : V K) : (straightPowerTable a b 0).mul r x = 0 :=
    straightBlockAnnihilator_mul a b x
  have hrRight (x : V K) : (straightPowerTable a b 0).mul x r = 0 :=
    straightBlock_mul_annihilator a b x
  let E := basisEquivOfTripleIndependent hlin
  let T : TableEquiv (fixedTable (K := K) .s4) (straightPowerTable a b 0) :=
    TableEquiv.ofBasis E (by
      intro i j
      fin_cases i <;> fin_cases j <;>
        simp [fixedTable, E, hpp, hpq, hqp, hqq, hrLeft, hrRight])
  exact ⟨T.symm⟩

/-- A nonzero square root of one quarter of the discriminant gives the split
block `S3`. -/
theorem straightPowerTable_isomorphic_s3_of_square [CharZero K]
    (a b s : K) (hb : b ≠ 0) (hs : s * s = straightDiscriminant a b / 4)
    (hs0 : s ≠ 0) : Isomorphic (straightPowerTable a b 0) (fixedTable .s3) := by
  let p := straightBlockUnit a b
  let f := straightCenteredGenerator a b
  let q : V K := s⁻¹ • f
  let r := straightBlockAnnihilator a b
  have hlin0 : TripleIndependent p f r :=
    straightCentered_tripleIndependent a b hb
  have hlin : TripleIndependent p q r := by
    exact tripleIndependent_smul_second hlin0 (inv_ne_zero hs0)
  have hpp : (straightPowerTable a b 0).mul p p = p :=
    straightBlockUnit_mul_self a b hb
  have hpf : (straightPowerTable a b 0).mul p f = f :=
    straightBlockUnit_mul_centered a b hb
  have hfp : (straightPowerTable a b 0).mul f p = f :=
    straightCentered_mul_blockUnit a b hb
  have hpq : (straightPowerTable a b 0).mul p q = q := by
    change (straightPowerTable a b 0).mul p (s⁻¹ • f) = s⁻¹ • f
    change (mulLinear (straightPowerTable a b 0) p) (s⁻¹ • f) = _
    rw [map_smul, mulLinear_apply, hpf]
  have hqp : (straightPowerTable a b 0).mul q p = q := by
    change (straightPowerTable a b 0).mul (s⁻¹ • f) p = s⁻¹ • f
    simpa [hfp] using mul_smul_smul_three
      (straightPowerTable a b 0) s⁻¹ 1 f p
  have hqq : (straightPowerTable a b 0).mul q q = p := by
    calc
      (straightPowerTable a b 0).mul q q =
          (s⁻¹ * s⁻¹) • (straightPowerTable a b 0).mul f f := by
        exact mul_smul_smul_three (straightPowerTable a b 0) s⁻¹ s⁻¹ f f
      _ = (s⁻¹ * s⁻¹) •
          ((straightDiscriminant a b / 4) • p) := by
        rw [straightCentered_mul_self a b hb]
      _ = p := by
        rw [← hs]
        rw [smul_smul]
        have hcoef : s⁻¹ * s⁻¹ * (s * s) = 1 := by
          field_simp [hs0]
        rw [hcoef, one_smul]
  have hrLeft (x : V K) : (straightPowerTable a b 0).mul r x = 0 :=
    straightBlockAnnihilator_mul a b x
  have hrRight (x : V K) : (straightPowerTable a b 0).mul x r = 0 :=
    straightBlock_mul_annihilator a b x
  let E := basisEquivOfTripleIndependent hlin
  let T : TableEquiv (fixedTable (K := K) .s3) (straightPowerTable a b 0) :=
    TableEquiv.ofBasis E (by
      intro i j
      fin_cases i <;> fin_cases j <;>
        simp [fixedTable, E, hpp, hpq, hqp, hqq, hrLeft, hrRight])
  exact ⟨T.symm⟩

/-- A square root of minus one quarter of the discriminant gives the real-only
complex block.  The statement is field-generic; it is instantiated over `ℝ`
below. -/
theorem straightPowerTable_isomorphic_straightMinus_of_negativeSquare
    [CharZero K] (a b s : K) (hb : b ≠ 0)
    (hs : s * s = -(straightDiscriminant a b / 4)) (hs0 : s ≠ 0) :
    Isomorphic (straightPowerTable a b 0) realStraightMinusTable := by
  let p := straightBlockUnit a b
  let f := straightCenteredGenerator a b
  let q : V K := s⁻¹ • f
  let r := straightBlockAnnihilator a b
  have hlin0 : TripleIndependent p f r :=
    straightCentered_tripleIndependent a b hb
  have hlin : TripleIndependent p q r := by
    exact tripleIndependent_smul_second hlin0 (inv_ne_zero hs0)
  have hpp : (straightPowerTable a b 0).mul p p = p :=
    straightBlockUnit_mul_self a b hb
  have hpf : (straightPowerTable a b 0).mul p f = f :=
    straightBlockUnit_mul_centered a b hb
  have hfp : (straightPowerTable a b 0).mul f p = f :=
    straightCentered_mul_blockUnit a b hb
  have hpq : (straightPowerTable a b 0).mul p q = q := by
    change (straightPowerTable a b 0).mul p (s⁻¹ • f) = s⁻¹ • f
    change (mulLinear (straightPowerTable a b 0) p) (s⁻¹ • f) = _
    rw [map_smul, mulLinear_apply, hpf]
  have hqp : (straightPowerTable a b 0).mul q p = q := by
    change (straightPowerTable a b 0).mul (s⁻¹ • f) p = s⁻¹ • f
    simpa [hfp] using mul_smul_smul_three
      (straightPowerTable a b 0) s⁻¹ 1 f p
  have hqq : (straightPowerTable a b 0).mul q q = -p := by
    calc
      (straightPowerTable a b 0).mul q q =
          (s⁻¹ * s⁻¹) • (straightPowerTable a b 0).mul f f := by
        exact mul_smul_smul_three (straightPowerTable a b 0) s⁻¹ s⁻¹ f f
      _ = (s⁻¹ * s⁻¹) •
          ((straightDiscriminant a b / 4) • p) := by
        rw [straightCentered_mul_self a b hb]
      _ = -p := by
        have hdisc : straightDiscriminant a b / 4 = -(s * s) := by
          calc
            straightDiscriminant a b / 4 = -(-(straightDiscriminant a b / 4)) := by
              simp
            _ = -(s * s) := by rw [hs]
        rw [hdisc]
        rw [smul_smul]
        have hcoef : s⁻¹ * s⁻¹ * (-(s * s)) = -1 := by
          field_simp [hs0]
        rw [hcoef, neg_one_smul]
  have hrLeft (x : V K) : (straightPowerTable a b 0).mul r x = 0 :=
    straightBlockAnnihilator_mul a b x
  have hrRight (x : V K) : (straightPowerTable a b 0).mul x r = 0 :=
    straightBlock_mul_annihilator a b x
  let E := basisEquivOfTripleIndependent hlin
  let T : TableEquiv (realStraightMinusTable (K := K))
      (straightPowerTable a b 0) :=
    TableEquiv.ofBasis E (by
      intro i j
      fin_cases i <;> fin_cases j <;>
        simp [realStraightMinusTable, E, hpp, hpq, hqp, hqq, hrLeft, hrRight])
  exact ⟨T.symm⟩

/-! ## Field-specific discriminant classification -/

theorem complex_straightPowerTable_classification (a b : ℂ) :
    Isomorphic (straightPowerTable a b 0) (fixedTable .s1) ∨
      Isomorphic (straightPowerTable a b 0) (fixedTable .s2) ∨
      Isomorphic (straightPowerTable a b 0) (fixedTable .s3) ∨
      Isomorphic (straightPowerTable a b 0) (fixedTable .s4) := by
  by_cases hb : b = 0
  · subst b
    by_cases ha : a = 0
    · subst a
      left
      rw [straightPowerTable_zero_zero_eq_s1]
      exact Isomorphic.refl _
    · exact Or.inr (Or.inl (straightPowerTable_b_zero_isomorphic_s2 a ha))
  · by_cases hD : straightDiscriminant a b = 0
    · exact Or.inr (Or.inr (Or.inr
        (straightPowerTable_discriminant_zero_isomorphic_s4 a b hb hD)))
    · obtain ⟨s, hsPow⟩ := IsAlgClosed.exists_pow_nat_eq
        (straightDiscriminant a b / 4) (by norm_num : 0 < 2)
      have hs : s * s = straightDiscriminant a b / 4 := by
        simpa [pow_two] using hsPow
      have hs0 : s ≠ 0 := by
        have hquarter : straightDiscriminant a b / 4 ≠ 0 :=
          div_ne_zero hD (by norm_num)
        intro hsZero
        apply hquarter
        rw [← hs]
        simp [hsZero]
      exact Or.inr (Or.inr (Or.inl
        (straightPowerTable_isomorphic_s3_of_square a b s hb hs hs0)))

theorem real_straightPowerTable_classification (a b : ℝ) :
    Isomorphic (straightPowerTable a b 0) (fixedTable .s1) ∨
      Isomorphic (straightPowerTable a b 0) (fixedTable .s2) ∨
      Isomorphic (straightPowerTable a b 0) (fixedTable .s3) ∨
      Isomorphic (straightPowerTable a b 0) (fixedTable .s4) ∨
      Isomorphic (straightPowerTable a b 0) realStraightMinusTable := by
  by_cases hb : b = 0
  · subst b
    by_cases ha : a = 0
    · subst a
      left
      rw [straightPowerTable_zero_zero_eq_s1]
      exact Isomorphic.refl _
    · exact Or.inr (Or.inl (straightPowerTable_b_zero_isomorphic_s2 a ha))
  · rcases lt_trichotomy (straightDiscriminant a b) 0 with hneg | hzero | hpos
    · have hquarter : 0 < -(straightDiscriminant a b / 4) := by
        have : straightDiscriminant a b / 4 < 0 :=
          div_neg_of_neg_of_pos hneg (by norm_num)
        exact neg_pos.mpr this
      let s : ℝ := Real.sqrt (-(straightDiscriminant a b / 4))
      have hs : s * s = -(straightDiscriminant a b / 4) := by
        simpa [s, pow_two] using Real.sq_sqrt hquarter.le
      have hs0 : s ≠ 0 := by
        exact ne_of_gt (Real.sqrt_pos.2 hquarter)
      exact Or.inr (Or.inr (Or.inr (Or.inr
        (straightPowerTable_isomorphic_straightMinus_of_negativeSquare
          a b s hb hs hs0))))
    · exact Or.inr (Or.inr (Or.inr (Or.inl
        (straightPowerTable_discriminant_zero_isomorphic_s4 a b hb hzero))))
    · have hquarter : 0 < straightDiscriminant a b / 4 :=
        div_pos hpos (by norm_num)
      let s : ℝ := Real.sqrt (straightDiscriminant a b / 4)
      have hs : s * s = straightDiscriminant a b / 4 := by
        simpa [s, pow_two] using Real.sq_sqrt hquarter.le
      have hs0 : s ≠ 0 := by
        exact ne_of_gt (Real.sqrt_pos.2 hquarter)
      exact Or.inr (Or.inr (Or.inl
        (straightPowerTable_isomorphic_s3_of_square a b s hb hs hs0)))

/-- Complete coverage of the complex nonunital straight sector. -/
theorem complex_straight_sector_coverage
    (c : StructureConstants ℂ 3) (ha : c.MultiplicationAssociative)
    (hsector : InSector c .straight) : CoveredByComplexCandidates c := by
  obtain ⟨a, b, hab⟩ := nonunital_straight_isomorphic_powerTable_zero ha hsector
  rcases complex_straightPowerTable_classification a b with h | h | h | h
  · exact ⟨.fixed .s1, by simpa [complexCandidateTable] using hab.trans h⟩
  · exact ⟨.fixed .s2, by simpa [complexCandidateTable] using hab.trans h⟩
  · exact ⟨.fixed .s3, by simpa [complexCandidateTable] using hab.trans h⟩
  · exact ⟨.fixed .s4, by simpa [complexCandidateTable] using hab.trans h⟩

/-- Complete coverage of the real nonunital straight sector. -/
theorem real_straight_sector_coverage
    (c : StructureConstants ℝ 3) (ha : c.MultiplicationAssociative)
    (hsector : InSector c .straight) : CoveredByRealCandidates c := by
  obtain ⟨a, b, hab⟩ := nonunital_straight_isomorphic_powerTable_zero ha hsector
  rcases real_straightPowerTable_classification a b with h | h | h | h | h
  · exact ⟨.fixed .s1, by simpa [realCandidateTable] using hab.trans h⟩
  · exact ⟨.fixed .s2, by simpa [realCandidateTable] using hab.trans h⟩
  · exact ⟨.fixed .s3, by simpa [realCandidateTable] using hab.trans h⟩
  · exact ⟨.fixed .s4, by simpa [realCandidateTable] using hab.trans h⟩
  · exact ⟨.straightMinus, by simpa [realCandidateTable] using hab.trans h⟩

end CodexAIGC.DimensionThreeRealComplex
